### ISSUE TITLE
Missing sbt-assembly plugin

### ISSUE THREAD

**Issue by Fabryprog** [supermariolabs/spooq#1]
I am trying to import project to intellij. There is a missing sbt dependency

`/Users/fabrizio/Documents/workspace_personal/spooq/build.sbt:58: error: not found: value assembly
assembly / mainClass := Some("com.github.supermariolabs.spooq.Application")
^
[error] Type error in expression`

**Comment by supermariolabs** [comment]
Merged, thanks for the contribution!
